/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xiaoyuan_jnitestsample_JNIUtil */

#ifndef _Included_com_xiaoyuan_jnitestsample_JNIUtil
#define _Included_com_xiaoyuan_jnitestsample_JNIUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xiaoyuan_jnitestsample_JNIUtil
 * Method:    getWorld
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_xiaoyuan_jnitestsample_JNIUtil_getWorld
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
